# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: book.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'book.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nbook.proto\x12\x0b\x62ookcatalog\"?\n\x04\x42ook\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\x0c\n\x04year\x18\x04 \x01(\x05\"\x12\n\x10ListBooksRequest\"5\n\x11ListBooksResponse\x12 \n\x05\x62ooks\x18\x01 \x03(\x0b\x32\x11.bookcatalog.Book\"=\n\x0e\x41\x64\x64\x42ookRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x02 \x01(\t\x12\x0c\n\x04year\x18\x03 \x01(\x05\"2\n\x0f\x41\x64\x64\x42ookResponse\x12\x1f\n\x04\x62ook\x18\x01 \x01(\x0b\x32\x11.bookcatalog.Book2\x9f\x01\n\x0b\x42ookCatalog\x12J\n\tListBooks\x12\x1d.bookcatalog.ListBooksRequest\x1a\x1e.bookcatalog.ListBooksResponse\x12\x44\n\x07\x41\x64\x64\x42ook\x12\x1b.bookcatalog.AddBookRequest\x1a\x1c.bookcatalog.AddBookResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'book_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BOOK']._serialized_start=27
  _globals['_BOOK']._serialized_end=90
  _globals['_LISTBOOKSREQUEST']._serialized_start=92
  _globals['_LISTBOOKSREQUEST']._serialized_end=110
  _globals['_LISTBOOKSRESPONSE']._serialized_start=112
  _globals['_LISTBOOKSRESPONSE']._serialized_end=165
  _globals['_ADDBOOKREQUEST']._serialized_start=167
  _globals['_ADDBOOKREQUEST']._serialized_end=228
  _globals['_ADDBOOKRESPONSE']._serialized_start=230
  _globals['_ADDBOOKRESPONSE']._serialized_end=280
  _globals['_BOOKCATALOG']._serialized_start=283
  _globals['_BOOKCATALOG']._serialized_end=442
# @@protoc_insertion_point(module_scope)
